//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.TechicalTariff = new HashSet<TechicalTariff>();
        }
    
        public int IdBooking { get; set; }
        public int IdUsers { get; set; }
        public int IdTechnicalTariff { get; set; }
        public System.DateTime StartDateBooking { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> EndDateBooking { get; set; }
        public int IdAdministrotor { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<TechicalTariff> TechicalTariff { get; set; }
    }
}
