//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int IdBooking { get; set; }
        public int IdUsers { get; set; }
        public int IdTariff { get; set; }
        public int IdTechnical { get; set; }
        public System.DateTime StartDateBooking { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> EndDateBooking { get; set; }
        public int IdAdministrotor { get; set; }
    
        public virtual TariffRents TariffRents { get; set; }
        public virtual Technic Technic { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
