//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffRents
    {
        public TariffRents()
        {
            this.TechicalTariff = new HashSet<TechicalTariff>();
        }
    
        public int IdTariff { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TechicalTariff> TechicalTariff { get; set; }
    }
}
