//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechicalTariff
    {
        public int IdTechnicalTariff { get; set; }
        public int IdTechical { get; set; }
        public int IdTariff { get; set; }
        public int IdBooking { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual TariffRents TariffRents { get; set; }
        public virtual Technic Technic { get; set; }
    }
}
