//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technic
    {
        public Technic()
        {
            this.TechicalTariff = new HashSet<TechicalTariff>();
        }
    
        public int IdTechnical { get; set; }
        public string Name { get; set; }
        public string VIN { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<TechicalTariff> TechicalTariff { get; set; }
    }
}
