//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programm.Modl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Booking = new HashSet<Booking>();
            this.Booking1 = new HashSet<Booking>();
        }
    
        public int IdUser { get; set; }
        public string FullName { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PassportData { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<Booking> Booking1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
